### PR TITLE
Adds Swedish language 🇸🇪

### PR DESCRIPTION
**Pull request by Jacalz**
This commit just adds Swedish localized strings to the app 👍
Closes: #51

### CODE REVIEW

**Comment by Jacalz** [comment]
Any update on this? @invariant

**Comment by Jacalz** [comment]
Not that I think this PR will ever get merged, but I will keep it open anyway :+1:

**Comment by invariant** [comment]
What you mean a year is not soon enough? :/
Yeah, I'm a bit behind...

**Comment by Jacalz** [comment]
Sorry did not mean to be rude, just thought that you had stopped using your github account. Happy New Years 🍾🎊

**Comment by invariant** [comment]
And to you! Thank for your contribution and I expect I will merge it when I next update the app.

**Pull request merged**
